CREATE TABLE PROFILE (
	ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    NM_ROLE VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO PROFILE(NM_ROLE) VALUES('ADM');
INSERT INTO PROFILE(NM_ROLE) VALUES('NORMAL');