CREATE TABLE USER (
	ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    NM_USER VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(250) NOT NULL,
    PROFILE_ID BIGINT(20),
    FOREIGN KEY (PROFILE_ID) REFERENCES PROFILE(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO USER(nm_user, email, password, PROFILE_ID) VALUES('Leonardo', 'leonardo@gmail.com', '$2a$10$zeFLj8x8.3ENQoh9treEueSjg4XPjvsk.BvUB5zmq81kqxJeVL8Ji', 1);
